### ISSUE TITLE
Ajout de fonctionnalités

### ISSUE THREAD

**Issue by iR3SH** [Thomas-Anonymous/CommunityTools#1]
Salut, pas mal ton projet j'ai ajouté un filtre pour sniffer les maps si jamais tu veux le rajouter aussi c'est assez utile

**Comment by Thomas-Anonymous** [comment]
Salut, le logiciel à beaucoup évolué depuis la mise en ligne, je travail sur une lecture séparé 2.0 / 1.29, j'ai ajouté un lecteur de packet 2.0, je travail sur la lecture des maps et mobs, le soucis c'est que j'ai très peu de temps surtout en ce moment beaucoup de projets qui arrivent à termes IRL donc encore moins de temps :)

Quand j'aurais fini la détecter de ce que je voulais je mettrais à jour, la détection de maps 1.29 est assez facile comparé à la 2.0 :D

Merci quand même pour la proposition, il me semble que tu peux proposer des modifications quelque part sur GitHub je sais plus vraiment où, n'hésite pas à en faire la demande 👍

**Comment by iR3SH** [comment]
Ca marche et je comprends c'est pas une priorité :p 

Je vais le continuer aussi de mon côté !

Merci pour ton partage en tout cas !
